---

- name: Fail if required tsdproxy settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - tsdproxy_uid
    - tsdproxy_gid
    - tsdproxy_docker_endpoint
    - tsdproxy_controlurl
